apps/login_registration/urls.py
from django.conf.urls import url
from . import views

app_name = 'login_registration'

urlpatterns = [
    # # registers user info if all info is valid
    url(r'^register$', views.register, name='register'),
    # logs in user if user info is valid and saves info into a session
    url(r'^login$', views.login, name='login'),
    # logs out a user and deletes session containing user info
    url(r'^logout$', views.logout, name='logout')
]

apps/trailblazr/urls.py
from django.conf.urls import url
from . import views

app_name = 'trailblazr'

urlpatterns = [
    # displays user login and registration page
    url(r'^$', views.index, name='index'),
    # displays user dashboard
    url(r'dashboard$', views.dashboard, name='dashboard'),
    # displays search results and search bar
    url(r'^search_bar$', views.search_bar, name='search_bar'),
    # searches for trails near specific location
    url(r'^search$', views.search, name='search'),
    # adds trail to user's dashboard
    url(r'^add_trail/(?P<id>\d+)$', views.add_trail, name='add_trail'),
    # deletes specific trail
    url(r'del_trail/(?P<id>\d+)$', views.del_trail, name='del_trail'),
    # # displays specific trail page
    url(r'trail/(?P<id>\d+)$', views.show_trail, name='show_trail')
]

trailblazr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.trailblazr.urls', namespace='trailblazr')),
    path('login_registration/', include('apps.login_registration.urls', namespace='login_registration'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/trailblazr/models.py
from django.db import models
from datetime import datetime
from ..login_registration.models import User
from enum import Enum

class TrailManager(models.Manager):
    def add_trail(self, user_id, trail_id, trail_name, trail_location, trail_lat, trail_lon, trail_length, trail_ascent, trail_descent, trail_difficulty):
        user = User.objects.get(id=user_id)
        trail_id = trail_id
        trail_name = trail_name
        trail_location = trail_location
        trail_lat = trail_lat
        trail_lon = trail_lon
        trail_length = trail_length
        trail_ascent = trail_ascent
        trail_descent = trail_descent
        trail_difficulty = trail_difficulty
        trail = Trail.objects.create(user=user, trail_id=trail_id, name=trail_name, location=trail_location, lat=trail_lat, lon=trail_lon, length=trail_length, ascent=trail_ascent, descent=trail_descent, difficulty=trail_difficulty)
        return trail

class Trail(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    trail_id = models.IntegerField()
    name = models.CharField(max_length=255, default='')
    location = models.CharField(max_length=255, default='')
    lat = models.FloatField(default=0)
    lon = models.FloatField(default=0)
    length = models.FloatField(default=0)
    ascent = models.FloatField(default=0)
    descent = models.FloatField(default=0)
    class DifficultyOptions(Enum):
        BEGINNER = 'Beginner'
        INTERMEDIATE = 'Intermediate'
        ADVANCED = 'Advanced'

        @classmethod
        def choices(cls):
            return [(key.value, key.name) for key in cls]
    difficulty = models.CharField(max_length=12, choices=DifficultyOptions.choices(), default='Beginner')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = TrailManager()

    def __str__(self):
        return "{}".format(self.trail_id)

apps/trailblazr/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .models import Trail
from ..login_registration.models import User
import requests
from django.conf import settings

# displays landing page
def index(request):
    return render(request, 'index.html')

# displays user dashboard, including list of trails saved by current user if there are any
def dashboard(request):
    user = User.objects.get(id=request.session['user_id'])
    try:
        trails = Trail.objects.filter(user=user).order_by('created_at')
    except Trail.DoesNotExist:
        trails = None
    context = {
        'trails': trails
    }
    return render(request, 'dashboard.html', context)

# displays search page
def search_bar(request):
    return render(request, 'results.html')

# makes api call to Google Maps to retrieve latitude and longitude coordinates
# makes api call to Hiking Project using lat and lon to retrieve list of trails near queried location
def search(request):
    if 'search' in request.GET:
        address = request.GET['search']
        address_list = address.split(' ');
        address = ''
        for i in range(len(address_list)):
            address = address + address_list[i] + "+"
        response = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address={}&key={}'.format(address, settings.GOOGLE_MAPS_API_KEY)) 
        location = response.json()
        lat = location['results'][0]['geometry']['location']['lat']
        lon = location['results'][0]['geometry']['location']['lng']
        response = requests.get('https://www.hikingproject.com/data/get-trails?lat={}&lon={}&key={}'.format(lat, lon, settings.HIKING_PROJECT_API_KEY))
        trails = response.json()
        results = trails['trails']
        user_trails = Trail.objects.filter(user=request.session['user_id'])
        saved_trails = []
        for user_trail in user_trails:
            saved_trails.append(user_trail.trail_id)
        context = {
            'results': results,
            'address': address,
            'saved_trails': saved_trails
        }
        return render(request, 'results.html', context)
    else:
        return redirect('trailblazr:dashboard')

# saves selected trail into user's saved trails list
def add_trail(request, id):
    response = requests.get('https://www.hikingproject.com/data/get-trails-by-id?ids={}&key={}'.format(id, settings.HIKING_PROJECT_API_KEY))
    trail = response.json()
    trail_id = trail['trails'][0]['id']
    trail_name = trail['trails'][0]['name']
    trail_location = trail['trails'][0]['location']
    trail_lat = trail['trails'][0]['latitude']
    trail_lon = trail['trails'][0]['longitude']
    trail_length = trail['trails'][0]['length']
    trail_ascent = trail['trails'][0]['ascent']
    trail_descent = trail['trails'][0]['descent']
    if trail['trails'][0]['difficulty'] == 'green':
        trail_difficulty = 'Beginner'
    elif trail['trails'][0]['difficulty'] == 'blue':
        trail_difficulty = 'Intermediate'
    elif trail['trails'][0]['difficulty'] == 'black':
        trail_difficulty = 'Advanced'
    Trail.objects.add_trail(request.session['user_id'], trail_id, trail_name, trail_location, trail_lat, trail_lon, trail_length, trail_ascent, trail_descent, trail_difficulty)
    return redirect('trailblazr:search')

# deletes selected trail from user's saved trails list
def del_trail(request, id):
    Trail.objects.get(id=id).delete()
    return redirect('trailblazr:dashboard')

# makes api call to Hiking Project to gather additional info about specific trail
# makes api call to Google Maps to embed map of trail location
def show_trail(request, id):
    trail = Trail.objects.get(id=id)
    address = trail.name
    address_list = address.split(' ')
    address = ''
    for i in range(len(address_list)):
        address = address + address_list[i] + "+"
    response = requests.get('https://www.hikingproject.com/data/get-conditions?ids={}&key={}'.format(trail.trail_id, settings.HIKING_PROJECT_API_KEY))
    conditions = response.json()
    context = {
        'trail': trail,
        'address': address,
        'conditions': conditions['0'],
        'google_maps_api_key': settings.GOOGLE_MAPS_API_KEY 
    }
    return render(request, 'trail.html', context)

apps/trailblazr/templates/dashboard.html
<!doctype html>
<html lang="en-US">
<head>
    <title>Trailblazr</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="HandheldFriendly" content="true">
    <meta name="description" content="Hiking app that lets users find trails to hike nearby!">
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text&family=Jost&display=swap" rel="stylesheet" async>
    <link href='https://css.gg/home.css' rel='stylesheet' async>
    <link href='https://css.gg/search.css' rel='stylesheet' async>
    <link href='https://css.gg/log-out.css' rel='stylesheet' async>
    {% load static %} 
    <link rel="stylesheet" href="{% static 'scss/theme.css' %}" async>
</head>
<body>
    <div id="main">
        <div id="dashboard">
            <div class="container">
                {% if trails %}
                    <ul>
                        {% for trail in trails %}
                            <li>
                                <a href="{% url 'trailblazr:show_trail' id=trail.id %}">
                                    <div class="card">
                                        <h3 class="card-title">{{ trail.name }}</h3>
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-6">
                                                    <p>
                                                        <svg width="16px" height="16px" viewBox="0 0 60 60">
                                                            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                                <g id="icon" transform="translate(-9.000000, -3.000000)" fill="#000000" stroke="#000000">
                                                                    <path d="M32,60 C17.3333333,43.3637967 10,31.3637967 10,24 C10,12.954305 19.8497355,4 32,4 C44.1502645,4 54,12.954305 54,24 C54,31.3637967 46.6666667,43.3637967 32,60 Z M32,34 C37.5228475,34 42,29.5228475 42,24 C42,18.4771525 37.5228475,14 32,14 C26.4771525,14 22,18.4771525 22,24 C22,29.5228475 26.4771525,34 32,34 Z" id="Combined-Shape"></path>
                                                                </g>
                                                            </g>
                                                        </svg>
                                                        {{ trail.location }}
                                                    </p>
                                                </div>
                                                <div class="col-6">
                                                    <p>{{ trail.difficulty }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="message">
                        <h3>You haven't saved any trails yet! Time to start exploring!</h3>
                        <img src="{% static 'img/mountain2.webp' %}" alt="Mountain Image">
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <nav class="navbar navbar-custom fixed-bottom" id="navbar">
        <ul class="navbar-nav">
            <div class="row">
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'trailblazr:dashboard' %}"><i class="gg-home"></i> </a>
                    </li>
                </div>
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'trailblazr:search_bar' %}"><i class="gg-search"></i></a>
                    </li>
                </div>
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login_registration:logout' %}"><i class="gg-log-out"></i></a>
                    </li>
                </div>
            </div>
        </ul> 
    </nav>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

apps/trailblazr/templates/results.html
<!doctype html>
<html lang="en-US">
<head>
    <title>Trailblazr</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="HandheldFriendly" content="true">
    <meta name="description" content="Hiking app that lets users find trails to hike nearby!">
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text&family=Jost&display=swap" rel="stylesheet" async>
    <link href='https://css.gg/home.css' rel='stylesheet' async>
    <link href='https://css.gg/search.css' rel='stylesheet' async>
    <link href='https://css.gg/log-out.css' rel='stylesheet' async>
    {% load static %}
    <link rel="stylesheet" href="{% static 'scss/theme.css' %}" async>
</head>
<body>
    <div id="main">
        <div id="search">
            <div class="container fixed-top">
                <form class="form-inline d-flex justfy-content-center" action="{% url 'trailblazr:search' %}" method="get">
                    <a class="nav-link" href="{% url 'trailblazr:search_bar' %}"><i class="gg-search"></i></a>
                    <input class="search-bar form-control w-75" type="text" name="search" placeholder="Search" aria-labelledby="Search">
                </form>
            </div>
        </div>
        <div id="results">
            <div class="container">
                {% if results %}
                    <ul>
                        {% for result in results %}
                            <li>
                                <div class="card">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col">
                                                <h3>{{ result.name }}</h3>
                                                <p>
                                                    <svg width="16px" height="16px" viewBox="0 0 60 60">
                                                        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                            <g id="icon" transform="translate(-9.000000, -3.000000)" fill="#000000" stroke="#000000">
                                                                <path d="M32,60 C17.3333333,43.3637967 10,31.3637967 10,24 C10,12.954305 19.8497355,4 32,4 C44.1502645,4 54,12.954305 54,24 C54,31.3637967 46.6666667,43.3637967 32,60 Z M32,34 C37.5228475,34 42,29.5228475 42,24 C42,18.4771525 37.5228475,14 32,14 C26.4771525,14 22,18.4771525 22,24 C22,29.5228475 26.4771525,34 32,34 Z" id="Combined-Shape"></path>
                                                            </g>
                                                        </g>
                                                    </svg>
                                                    {{ result.location }}
                                                </p>
                                            </div>
                                            {% if result.id not in saved_trails %}
                                                <div class="float-right mr-2">
                                                    <a class="btn btn-pastel-pink" href="{% url 'trailblazr:add_trail' id=result.id %}">Save</a>
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="row">
                                            <div class="col-6">
                                                <p class="detail">{{ result.length }} mi. </p>
                                                <span>Length</span>
                                            </div>
                                            <div class="col-6">
                                                {% if result.difficulty == 'green' %}
                                                    <p class="detail">Beginner</p>
                                                {% elif result.difficulty == 'blue' %}
                                                    <p class="detail">Intermediate</p>
                                                {% elif result.difficulty == 'black' %}
                                                    <p class="detail">Advanced</p>
                                                {% endif %}
                                                <span>Difficulty</span>
                                            </div>
                                        </div>
                                    </div>  
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="message">
                        <h2 class="text-center">Time to start exploring! Find popular trails near you!</h2>
                        <img src="{% static 'img/mountain2.webp' %}" alt="Mountain Image">
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <nav class="navbar navbar-custom fixed-bottom" id="navbar">
        <ul class="navbar-nav">
            <div class="row">
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'trailblazr:dashboard' %}"><i class="gg-home"></i> </a>
                    </li>
                </div>
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'trailblazr:search_bar' %}"><i class="gg-search"></i></a>
                    </li>
                </div>
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login_registration:logout' %}"><i class="gg-log-out"></i></a>
                    </li>
                </div>
            </div>
        </ul> 
    </nav>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

apps/trailblazr/templates/trail.html
<!doctype html>
<html lang="en-US">
<head>
    <title>Trailblazr</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="HandheldFriendly" content="true">
    <meta name="description" content="Hiking app that lets users find trails to hike nearby!">
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text&family=Jost&display=swap" rel="stylesheet" async>
    <link href='https://css.gg/home.css' rel='stylesheet' async>
    <link href='https://css.gg/search.css' rel='stylesheet' async>
    <link href='https://css.gg/log-out.css' rel='stylesheet' async>
    <link href='https://css.gg/arrow-up-o.css' rel='stylesheet' async>
    <link href='https://css.gg/close-o.css' rel='stylesheet' async>
    {% load static %}
    <link rel="stylesheet" href="{% static 'scss/theme.css' %}" async>
    <link rel="stylesheet" href="{% static 'css/animation.css' %}" async>
</head>
<body>
    <div id="main">
        <div id="trail">
            <div class="container">
                <iframe
                    width="100%"
                    height="450"
                    frameborder="0" style="border:0"
                    src="https://www.google.com/maps/embed/v1/place?key={{ google_maps_api_key }}&q={{ address }}&center={{ trail.lat }},{{ trail.lon }}" 
                    allowfullscreen>
                </iframe>
            </div>
            <div class="container">
                <h2 class="text-uppercase text-center">{{ trail.name }}</h2>
                <i class="gg-arrow-up-o"></i>
            </div>
            <div id="details" class="hidden">
                <div class="container close">
                    <i class="gg-close-o"></i>
                </div>
                <div class="container">
                    <div class="header">
                        <h2 class="text-uppercase">{{ trail.name }}</h2>
                        <p>
                            <svg width="16px" height="16px" viewBox="0 0 60 60">
                                <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <g id="icon" transform="translate(-9.000000, -3.000000)" fill="#000000" stroke="#000000">
                                        <path d="M32,60 C17.3333333,43.3637967 10,31.3637967 10,24 C10,12.954305 19.8497355,4 32,4 C44.1502645,4 54,12.954305 54,24 C54,31.3637967 46.6666667,43.3637967 32,60 Z M32,34 C37.5228475,34 42,29.5228475 42,24 C42,18.4771525 37.5228475,14 32,14 C26.4771525,14 22,18.4771525 22,24 C22,29.5228475 26.4771525,34 32,34 Z" id="Combined-Shape"></path>
                                    </g>
                                </g>
                            </svg>
                            {{ trail.location }}
                        </p>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <p class="detail">{{ trail.difficulty }}</p>
                            <span>Difficulty</span>
                        </div>
                        <div class="col-6">
                            <p class="detail">{{ trail.length }} mi.</p>
                            <span>Length</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <p class="detail">{{ trail.ascent }} ft.</p>
                            <span>Ascent</span>
                        </div>
                        <div class="col-6">
                            <p class="detail">{{ trail.descent }} ft.</p>
                            <span>Descent</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <p class="detail">{{ conditions.conditionStatus }}</p>
                            <span>Conditions</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <p class="detail">{{ conditions.conditionDetails }}</p>
                            <span>Details</span>
                        </div>
                    </div>
                    <div class="text-center">
                        <a class="btn btn-outline-pastel-pink" href="{% url 'trailblazr:del_trail' id=trail.id %}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-custom fixed-bottom" id="navbar">
        <ul class="navbar-nav">
            <div class="row">
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'trailblazr:dashboard' %}"><i class="gg-home"></i> </a>
                    </li>
                </div>
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'trailblazr:search_bar' %}"><i class="gg-search"></i></a>
                    </li>
                </div>
                <div class="col-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login_registration:logout' %}"><i class="gg-log-out"></i></a>
                    </li>
                </div>
            </div>
        </ul> 
    </nav>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>
        $(".gg-arrow-up-o").click(function() {
            $("#details").removeClass("hidden");
            $("#details").addClass("slide-in-bottom");
        })

        $(".gg-close-o").click(function() {
            $("#details").addClass("hidden");
        })
    </script>
</body>
</html>